# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python Package
on:
  push:
    tags:
      - v**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare Github environment
      uses: actions/checkout@v2
      run : echo '🐙'
    - name: Prepare Python
      uses: actions/setup-python@v2
      run : echo '🐍'
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        echo '💾'
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        echo '🔨'
        python -m build
    - run : echo '🚀'
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.EBCOMMANDER_TOKEN }}
